### PR TITLE
Adding MiniProject - Movie booking app

### PR DESCRIPTION
**Pull request by vansh1999**
Add mini Project
1. Added Movie Booking app
2. Used HTML/CSS/JS
3. Storing user-selected seats on LocalStrorage.
ss01
ss02
ss03

### CODE REVIEW

**Review by akshayysharma — APPROVED** [review]
Approved 👍

**Comment by vansh1999** [comment]
@akshayysharma Thanks Akshay for my first PR

**Comment by vansh1999** [comment]
@akshayysharma How can contribute more to this

**Comment by akshayysharma** [comment]
> @akshayysharma How can contribute more to this

@vansh1999, you can contribute a Leetcode solution, or a small web app just like you have submitted earlier. Hope this helps 👍

**Pull request merged**
