### PR TITLE
mini HTML Project

### PR DESCRIPTION
**Pull request by natzoz**
Created a new java class that decodes binary messages.

### CODE REVIEW

**Comment by natzoz** [comment]
Sorry I wanted to make these as two separate pull requests, but I will just make another pull request when I further update my skate HTML project if that is alright?

**Review by akshayysharma — APPROVED** [review]
Approved 👍

**Comment by akshayysharma** [comment]
> Sorry I wanted to make these as two separate pull requests, but I will just make another pull request when I further update my skate HTML project if that is alright?

Sure 😄

**Comment by natzoz** [comment]
Thank you!

**Pull request merged**
