### PR TITLE
added LRU Cache Leet Code

### PR DESCRIPTION
**Pull request by varishtsg**
Added python code for LRU Cache.
https://leetcode.com/problems/lru-cache/

For issue #5

### CODE REVIEW

**Review by akshayysharma — APPROVED** [review]
Approved 👍

**Comment by akshayysharma** [comment]
Merged 👍

**Comment by varishtsg** [comment]
Thanks. Do you have any other ideas, that you would like to be added :smile:

**Comment by akshayysharma** [comment]
> Thanks. Do you have any other ideas, that you would like to be added 😄

You can add any solution of Leetcode or you can create a small web application/webpage using your favorite library/framework. Hope that help :smiley:

**Pull request merged**
