### PR TITLE
Added a color guessing game using HTML,CSS and javascript

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**

### CODE REVIEW

**Review by akshayysharma — CHANGES_REQUESTED** [review]
Hey @96RadhikaJadhav, please remove the unnecessary EventListener in the .js file which are already commented. Rest everything is on good.

**Comment by 96RadhikaJadhav** [comment]
Done the changes, please review now.

**Review by akshayysharma — APPROVED** [review]
Approve 👍

**Comment by 96RadhikaJadhav** [comment]
@akshayysharma  Can't my PR be labelled as hacktoberfest-accepted?

**Comment by akshayysharma** [comment]
> @akshayysharma Can't my PR be labelled as hacktoberfest-accepted?

Hey @96RadhikaJadhav, I have already created an issue and labeled it as "hacktoberfest-accepted", so going forward if you are only doing open source, just for the sake of Hacktoberfest, you not need to worry about this, after merging your PR will count. Hope this helps 😄

**Pull request merged**
