### PR TITLE
Add solution to leetcode problem buddy strings

### PR DESCRIPTION
**Pull request by nehalabhasetwar**

### CODE REVIEW

**Review by akshayysharma — CHANGES_REQUESTED** [review]
Hey @nehalabhasetwar, can you please include the Problem statement in your code via comments, please 😄

**Comment by nehalabhasetwar** [comment]
Description:
Given two strings A and B of lowercase letters, return true if you can swap two letters in A so the result is equal to B, otherwise, return false.
Swapping letters is defined as taking two indices i and j (0-indexed) such that i != j and swapping the characters at A[i] and A[j]. For example, swapping at indices 0 and 2 in "abcd" results in "cbad".

Example1:
Input: A = "ab", B = "ba"
Output: true

Example2:
Input: A = "ab", B = "ab"
Output: false

**Comment by nehalabhasetwar** [comment]
@akshayysharma 
I have added description of problem , please review  it again.
Thank you in advance.

**Review by akshayysharma — APPROVED** [review]
Approved 👍

**Comment by nehalabhasetwar** [comment]
@akshayysharma  can you please add hacktoberfest-accepted label to PR #60 
Thank you in advance

**Pull request merged**
