### PR TITLE
Added an optimized algorithm to compute GCD

### PR DESCRIPTION
**Pull request by atharvakarnik**
Hey there! I have added an optimized algorithm to compute GCD of 2 numbers, about which, I have provided detailed insights in the README.md file.
This PR is with reference to issue #5.
Thank you!

### CODE REVIEW

**Review by akshayysharma — CHANGES_REQUESTED** [review]
Can you please remove the Readme file, All you can do is provide the (Description, Example, and Explanation) comments in your .py file.
But Altogether good work

**Comment by atharvakarnik** [comment]
> Can you please remove the Readme file, All you can do is provide the (Description, Example, and Explanation) comments in your .py file.
> But Altogether good work

Yes, sure! Thanks!

**Review by atharvakarnik — COMMENTED** [review]
Hey @akshayysharma, I have removed the README.md file and added the comments in the program.

**Review by akshayysharma — APPROVED** [review]
Perfect

**Pull request merged**
