### PR TITLE
Vuex (state management) based todo app added

### PR DESCRIPTION
**Pull request by asadkhalid305**
Created Todo App in VueJs using Vuex (state management).

Mock APIs are used from [here](https://jsonplaceholder.typicode.com)

**User Testcase:**
Screenshot 2020-10-18 at 2 27 43 AM

Screenshot 2020-10-18 at 2 27 49 AM

### CODE REVIEW

**Review by akshayysharma — COMMENTED** [review]
Not able to open the submodule to review the code! 😷

**Comment by asadkhalid305** [comment]
> Not able to open the submodule to review the code! 😷

Something messed up and code inside the main folder got removed. I was about to raise new PR to decline this one in order to add proper work but it has been merged meanwhile. Sorry for inconvenience.

**Comment by akshayysharma** [comment]
> > Not able to open the submodule to review the code! 😷
> 
> Something messed up and code inside the main folder got removed. I was about to raise new PR to decline this one in order to add proper work but it has been merged meanwhile. Sorry for inconvenience.

No problem @asadkhalid305 , I'll wait for your next PR 😄

**Comment by asadkhalid305** [comment]
> > > Not able to open the submodule to review the code! 😷
> > 
> > 
> > Something messed up and code inside the main folder got removed. I was about to raise new PR to decline this one in order to add proper work but it has been merged meanwhile. Sorry for inconvenience.
> 
> No problem @asadkhalid305 , I'll wait for your next PR 😄

In that case I have already raised correct one [PR](https://github.com/akshayysharma/hacktoberfest-2020/pull/37) :D

**Pull request merged**
