### PR TITLE
Hackerank solution "breaking the record problem"

### PR DESCRIPTION
**Pull request by andikanugraha11**

### CODE REVIEW

**Review by akshayysharma — CHANGES_REQUESTED** [review]
Hi @andikanugraha11, please add the problem statement in the file(in comments). Rest all the fine.

**Comment by andikanugraha11** [comment]
Okay, working for it.

**Comment by andikanugraha11** [comment]
Hi @akshayysharma, I have added a problem statement to my latest commit.

**Review by akshayysharma — APPROVED** [review]
Approved 👍

**Pull request merged**
